on:
  schedule:
    - cron: '0 10 * * 1-5' # 17:00 WIB
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install openpyxl yfinance pandas
      - run: python fetch-bei.py
      - run: git config user.name "bot" && git add saham.xlsx && git commit -m "auto 17:00" && git push
